CREATE TABLE [dbo].[MATCHUPS]
(
	[MATCHUP_ID] INT NOT NULL PRIMARY KEY, 
    [WINNER_ID] INT NOT NULL, 
    [MATCHUP_ROUND] INT NOT NULL, 
    CONSTRAINT [FK_MATCHUPS_ToTable] FOREIGN KEY ([WINNER_ID]) REFERENCES [TEAMS]([Team_Id])
)
