CREATE TABLE [dbo].[MATCHUP_ENTRIES]
(
	[MATCHUP_ENT_ID] INT NOT NULL PRIMARY KEY, 
    [MATCHUP_ID] INT NOT NULL, 
    [PARENT_MATCHUP_ID] INT NOT NULL, 
    [TEAM_COMPETING_ID] INT NOT NULL, 
    [SCORE] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_MATCHUP_ENTRIES_Teams] FOREIGN KEY ([TEAM_COMPETING_ID]) REFERENCES [TEAMS]([Team_Id]), 
    CONSTRAINT [FK_MATCHUP_ENTRIES_ToTable_1] FOREIGN KEY ([MATCHUP_ID]) REFERENCES [MATCHUPS]([MATCHUP_ID]) 
)
