CREATE TABLE [dbo].[Tournament_Entries]
(
	[TOUR_ENTRY_ID] INT NOT NULL PRIMARY KEY, 
    [TOURNAMENT_ID] INT NOT NULL, 
    [TEAM_ID] INT NOT NULL, 
    CONSTRAINT [FK_TEntry_Tour_ID] FOREIGN KEY ([TOURNAMENT_ID]) REFERENCES [TOURNAMENTS]([Tournament_Id]), 
    CONSTRAINT [FK_TEntry_Team_ID] FOREIGN KEY ([TEAM_ID]) REFERENCES [TEAMS]([Team_Id])
	
)
